# Generated by Django 4.1.4 on 2023-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_tag_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Файл'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
